PWA
GabrielDVpereira/NeteApp pull request #15
Opened 2022-11-04 02:26 UTC by gabibguedes

Add pwa configuration

2022-11-04 16:17 UTC, GabrielDVpereira requested changes

2022-11-04 16:17 UTC, GabrielDVpereira commented on public/offline.html
> +            <img src={logo} className="App-logo" alt="logo" />
Hey, the way of using images is different here, because it's an html file. I think you could put the logo under de public folder and reference it here as a relative path like "/logo"

2022-11-11 00:16 UTC, gabibguedes commented on public/offline.html
> +            <img src={logo} className="App-logo" alt="logo" />
fixed it

2022-11-11 00:19 UTC, GabrielDVpereira approved these changes
beautiful ❤️

2022-11-11 00:20 UTC, merged